routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	Route::get('/', function () {
    return view('auth.login');
  });
	Auth::routes();



/**
 * Admin Panel
 */
	Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {

  
		Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
		Route::group(['prefix'=>'bill'],function()
		{
		Route::resource('invoice','Admin\InvoiceController',['as'=>'admin.bill']);
		});
		Route::group(['prefix'=>'basic'],function()
		{
		Route::resource('category','Admin\CategoryController',['as'=>'admin.basic']);
		Route::resource('categorywise-rate','Admin\CategorywiseRateController',['as'=>'admin.basic'],['only'=>'index','create','store']);
		Route::resource('rate-type','Admin\RateTypeController',['as'=>'admin.basic']);
		});
	
	
		});
	

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $categoryList = Category::get();
        return view('admin.category.index',compact('categoryList'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

         return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [
            'name' =>$request->category_name,
        ];
        Category::create($data);
         session()->flash('flash_message','Category Created Successfully');
      return redirect()->back();
    
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\r  $r
     * @return \Illuminate\Http\Response
     */
    public function show(r $r)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\r  $r
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
       
          return view('admin.category.edit',compact('category'));
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\r  $r
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {
        //
        $data = ['name' =>$request->category_name,
                  'status' =>$request->status,  ];
                  $category->update($data);

    session()->flash('flash_message','Category Edited Successfully');
      return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\r  $r
     * @return \Illuminate\Http\Response
     */
    public function destroy(r $r)
    {
        //
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin.header')

@section('title',"Category")

@section('header-style')
@endsection
@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Category</strong> </li>
@endslot
@slot('title')
Add Category
@endslot
@endcomponent
@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
Add Category
@endslot
@slot('action')
	<a href="{{route('admin.basic.category.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
 @include('layouts.admin.success-error')
    <div class="panel-body"> 
			 	<form role="form" method="post" action="{{route('admin.basic.category.store')}}" class="validate"> 
			 		 {{ csrf_field() }}
                 <div class="col-md-12">
					 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Category Name</label> 
			 		    <div class="col-sm-4">  <input type="text"  class="form-control" name="category_name" data-validate="required"    data-message-required="This is Categroy Name for required field."   placeholder="Required Field"  /> </div>
			 		 </div>
			 		
			 		
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 </div>
 @endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin.header')

@section('title',"Category")

@section('header-style')
@endsection
@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Category</strong> </li>
@endslot
@slot('title')
Edit Category
@endslot
@endcomponent
@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
Edit Category
@endslot
@slot('action')
	<a href="{{route('admin.basic.category.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
 @include('layouts.admin.success-error')
    <div class="panel-body"> 
			 	<form role="form" action="{{route('admin.basic.category.update',$category->uuid)}}" method="post" class="validate"> 
			 			@method('PUT')
		 @csrf 
                 <div class="col-md-12">
					 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Category Name</label> 
			 		    <div class="col-sm-4">  <input type="text"  class="form-control" name="category_name" data-validate="required" value="{{$category->name}}"    data-message-required="This is Categroy Name for required field."   placeholder="Required Field"  /> </div>
			 		 </div>
			 		 <div class="form-group"> 
			 		 	<label class="col-sm-2 control-label">Status</label>
			 		 	 <div class="col-sm-4"> 
			 		 	  <select class="form-control" name="status" data-validate="required"   data-message-required="This is Status for required field." > 
			 		 	 			<option value="0" @if($category->status ==0) selected @endif>Active</option> 
			 		 	 			<option value="1" @if($category->status ==1) selected @endif>Inactive</option>  </select>
			 		 	 		</div> 

			 		 	 	</div> 

			 		
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 @endsection

resources/views/admin/category/index.blade.php
@extends('layouts.admin.header')

@section('title',"Category")

@section('header-style')
@endsection

@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Category</strong> </li>
@endslot
@slot('title')
 Category List
@endslot
@endcomponent
@endsection


@section('content-body')

<a href="{{route('admin.basic.category.create')}}" > <button type="button" class="btn btn-primary float-right">New Category</button> </a>
 <table class="table table-bordered datatable" id="table-4"> 

	<thead>
	 <tr>
	  <th>SNO</th> 
	  <th>Category Name</th> 
	  <th>Status</th>
	  <th>Action</th>
	 </tr>
	 </thead> 
	 <tbody>
	@foreach($categoryList as $count => $value)
	 	 <tr class="odd gradeA">
	  <td>{{++$count}}</td> 
	  <td>{{$value->name}}</td> 
	  <td>{!!$value->status()!!}</td> 
	   <td class="center"> {!! $value->action() !!}</td>
	   </tr> 
@endforeach
	   </tbody> 
	   <tfoot> 
	   	<tr>
	   	 <th>SNo</th> 
	   	 <th>Category Name</th>  
	   	 <th>Status</th>
	   	 <th>Action</th>
	   	 
	   	</tr> 
	   </tfoot> 
	</table> <br />
 
 <script type="text/javascript">
	jQuery( document ).ready( function( $ ) {
var $table4 = jQuery( "#table-4" );
$table4.DataTable( {
dom: 'Bfrtip',
buttons: [
'copyHtml5',
'excelHtml5',
'csvHtml5',
'pdfHtml5'
]
} );
} );
</script> <br />
@endsection 