routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	Route::get('/', function () {
    return view('auth.login');
  });
	Auth::routes();



/**
 * Admin Panel
 */
	Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {

  
		Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
		Route::group(['prefix'=>'bill'],function()
		{
		Route::resource('invoice','Admin\InvoiceController',['as'=>'admin.bill']);
		});
		Route::group(['prefix'=>'basic'],function()
		{
		Route::resource('category','Admin\CategoryController',['as'=>'admin.basic']);
		Route::resource('categorywise-rate','Admin\CategorywiseRateController',['as'=>'admin.basic'],['only'=>'index','create','store']);
		Route::resource('rate-type','Admin\RateTypeController',['as'=>'admin.basic']);
		});
	
	
		});
	

app/Http/Controllers/Admin/InvoiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class InvoiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.invoice.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.invoice.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/invoice/create.blade.php
@extends('layouts.admin.header')

@section('title',"Invoice")

@section('header-style')
@endsection
@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Invoice</strong> </li>
@endslot
@slot('title')
Add Invoice
@endslot
@endcomponent
@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
Add Invoice
@endslot
@slot('action')
	<a href="{{route('admin.bill.invoice.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
 @include('layouts.admin.success-error')
    <div class="panel-body"> 
			 	<form role="form" method="post" action="{{route('admin.bill.invoice.store')}}" class="validate"> 
			 		 {{ csrf_field() }}
            
				  <div class="row col-md-12">
					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Bill No</label> 
							<input type="text"  class="form-control" name="bill_no"   placeholder="Required Field"  />
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Customer Name</label> 
							<input type="text"  class="form-control" name="name" data-validate="required"    data-message-required="This is Customer Name for required field."   placeholder="Required Field"  />
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Bill Date</label> 
							<input type="text"  class="form-control" name="bill_date" data-validate="required"    data-message-required="This is Bill Date for required field."   placeholder="Required Field"  />
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Email</label> 
							<input type="text"  class="form-control" name="email" data-validate="required"    data-message-required="This is Email for required field."   placeholder="Required Field"  />
						</div>
					</div>

					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Mobile</label> 
							<input type="text"  class="form-control" name="mobile_number" data-validate="required"    data-message-required="This is Mobile for required field."   placeholder="Required Field"  />
						</div>
					</div>
					<div class="col-md-4">
						<div class="form-group">
							<label class=" control-label">Delivery Date</label> 
							<input type="text"  class="form-control" name="delivery_date" data-validate="required"    data-message-required="This is Bill Date for required field."   placeholder="Required Field"  />
						</div>
					</div>

				 </div>
			 		
			 		
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 </div>
 @endsection

resources/views/admin/invoice/edit.blade.php
@extends('layouts.admin.header')

@section('title',"Category")

@section('header-style')
@endsection
@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Category</strong> </li>
@endslot
@slot('title')
Edit Category
@endslot
@endcomponent
@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
Edit Category
@endslot
@slot('action')
	<a href="{{route('admin.basic.category.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
 @include('layouts.admin.success-error')
    <div class="panel-body"> 
			 	<form role="form" action="{{route('admin.basic.category.update',$category->uuid)}}" method="post" class="validate"> 
			 			@method('PUT')
		 @csrf 
                 <div class="col-md-12">
					 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Category Name</label> 
			 		    <div class="col-sm-4">  <input type="text"  class="form-control" name="category_name" data-validate="required" value="{{$category->name}}"    data-message-required="This is Categroy Name for required field."   placeholder="Required Field"  /> </div>
			 		 </div>
			 		 <div class="form-group"> 
			 		 	<label class="col-sm-2 control-label">Status</label>
			 		 	 <div class="col-sm-4"> 
			 		 	  <select class="form-control" name="status" data-validate="required"   data-message-required="This is Status for required field." > 
			 		 	 			<option value="0" @if($category->status ==0) selected @endif>Active</option> 
			 		 	 			<option value="1" @if($category->status ==1) selected @endif>Inactive</option>  </select>
			 		 	 		</div> 

			 		 	 	</div> 

			 		
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 @endsection

resources/views/admin/invoice/index.blade.php
@extends('layouts.admin.header')

@section('title',"Category")

@section('header-style')
@endsection

@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Invoice</strong> </li>
@endslot
@slot('title')
Invoice List
@endslot
@endcomponent
@endsection


@section('content-body')

<a href="{{route('admin.bill.invoice.create')}}" > <button type="button" class="btn btn-primary float-right">New Category</button> </a>
 <table class="table table-bordered datatable" id="table-4"> 

	<thead>
	 <tr>
	  <th>SNO</th> 
	  <th>Invoice Name</th> 
	  <th>Status</th>
	  <th>Action</th>
	 </tr>
	 </thead> 
	 <tbody>
	
	   </tbody> 
	   <tfoot> 
	   	<tr>
	   	 <th>SNo</th> 
	   	 <th>Category Name</th>  
	   	 <th>Status</th>
	   	 <th>Action</th>
	   	 
	   	</tr> 
	   </tfoot> 
	</table> <br />
 
 <script type="text/javascript">
	jQuery( document ).ready( function( $ ) {
var $table4 = jQuery( "#table-4" );
$table4.DataTable( {
dom: 'Bfrtip',
buttons: [
'copyHtml5',
'excelHtml5',
'csvHtml5',
'pdfHtml5'
]
} );
} );
</script> <br />
@endsection 