routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	Route::get('/', function () {
    return view('auth.login');
  });
	Auth::routes();



/**
 * Admin Panel
 */
	Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {

  
		Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
		Route::group(['prefix'=>'bill'],function()
		{
		Route::resource('invoice','Admin\InvoiceController',['as'=>'admin.bill']);
		});
		Route::group(['prefix'=>'basic'],function()
		{
		Route::resource('category','Admin\CategoryController',['as'=>'admin.basic']);
		Route::resource('categorywise-rate','Admin\CategorywiseRateController',['as'=>'admin.basic'],['only'=>'index','create','store']);
		Route::resource('rate-type','Admin\RateTypeController',['as'=>'admin.basic']);
		});
	
	
		});
	

app/Http/Controllers/Admin/RateTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\RateType;
use Webpatser\Uuid\Uuid;
class RateTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $rateType = RateType::get();
        return view('admin.rate-type.index',compact('rateType'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.rate-type.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

      
        $data =[
            'name'=>$request['name'],
            'type' => $request['type']?$request['type']:1,    
                ];
      RateType::create($data);
      session()->flash('flash_message','Rate Type Created Successfully');
      return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
       $rate_type =  RateType::where('uuid',$uuid)->first();
       return view('admin.rate-type.edit',compact('rate_type'));
        
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, RateType $rateType)
    {
        //
        $data = [
            'name' => $request['name'],
            'type' => $request['type']?$request['type']:1,
        ];
         $rateType->update($data);
         session()->flash('flash_message','Rate Type Updated Successfully');
      return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/rate-type/create.blade.php
@extends('layouts.admin.header')

@section('title',"Rate Type")

@section('header-style')
@endsection
@section('content-header')

@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Rate Type</strong> </li>
@endslot
@slot('title')
Rate Type
@endslot
@endcomponent



@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
	Add Rate Type
@endslot
@slot('action')
	<a href="{{route('admin.basic.rate-type.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
			  @include('layouts.admin.success-error')
			 <div class="panel-body"> 
			 	<form role="form" method="post" action="{{route('admin.basic.rate-type.store')}}"  class="validate"> 
		 {{ csrf_field() }}
                 <div class="col-md-12">
					 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Rate Type Name</label> 
			 		    <div class="col-sm-4">  <input type="text"  class="form-control" name="name" data-validate="required"    data-message-required="This is Rate Type for required field."   placeholder="Required Field"  /> </div>
			 		 </div>

			 		 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Fixed Rate</label> 
			 		    <div class="col-sm-4"> <div class="make-switch switch-mini" data-on-label="Yes" data-off-label="No"> <input type="checkbox" name="type" value="2"/> </div> </div>
			 		  
				</div>
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 </div>
 @endsection

resources/views/admin/rate-type/edit.blade.php
@extends('layouts.admin.header')

@section('title',"Rate Type")

@section('header-style')
@endsection
@section('content-header')

@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Rate Type</strong> </li>
@endslot
@slot('title')
Rate Type
@endslot
@endcomponent



@endsection
@section('content-body')

 <div class="row"> 
	<div class="col-md-12"> 
		<div class="panel panel-primary" data-collapsed="0"> 
@component('layouts.admin.components.header')
@slot('title')
	Edit Rate Type
@endslot
@slot('action')
	<a href="{{route('admin.basic.rate-type.index')}}" > <button type="button" class="btn btn-primary float-right">Back</button> </a>
@endslot
@endcomponent
			  @include('layouts.admin.success-error')
			 <div class="panel-body">
						 <form role="form" method="post" action="{{route('admin.basic.rate-type.update',$rate_type->id)}}"  class="validate"> 
					@method('PUT')
		 @csrf 
                 <div class="col-md-12">
					 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Rate Type Name</label> 
			 		    <div class="col-sm-4">  <input type="text"  class="form-control" name="name" data-validate="required" value="{{$rate_type->name}}"    data-message-required="This is Rate Type for required field."   placeholder="Required Field"  /> </div>
			 		 </div>

			 		 <div class="form-group">
			 		    <label class="col-sm-2 control-label">Fixed Rate</label> 
			 		    <div class="col-sm-4"> <div class="make-switch switch-mini" data-on-label="Yes" data-off-label="No"> <input type="checkbox" name="type"
			 		    @if($rate_type->type==2) checked @endif 
			 		    	value="2"/> </div> </div>
			 		  
				</div>
				<br>
				<br>
				<br>
				<div class="col-md-12">

                     <div class="form-group">  <div class="col-sm-6"></div>   <div class="col-sm-6 pull-left"><button type="submit" class="btn btn-success">Submit</button> <button type="reset" class="btn">Reset</button> </div> 
                     </div>
                     </div>
			 	</form> 
			 </div>
 	    </div>
 	</div>
 </div>
 </div>
 @endsection

resources/views/admin/rate-type/index.blade.php
@extends('layouts.admin.header')

@section('title',"Rate Type")

@section('header-style')
@endsection

@section('content-header')
@component('layouts.admin.components.breadcrumb')
@slot('breadcrumb')
<li> <a href="#">Basic</a> </li> 
<li class="active"> <strong>Rate Type</strong> </li>
@endslot
@slot('title')
 Rate Type List
@endslot
@endcomponent
@endsection


@section('content-body')

<a href="{{route('admin.basic.rate-type.create')}}" > <button type="button" class="btn btn-primary float-right">New Rate Type</button> </a>
 <table class="table table-bordered datatable" id="table-4"> 

	<thead>
	 <tr>
	  <th>SNO</th> 
	  <th>Category Name</th> 
	  <th>Status</th>
	 </tr>
	 </thead> 
	 <tbody>
	 	@foreach($rateType as $count => $value)
	 	 <tr class="odd gradeA">
	  <td>{{++$count}}</td> 
	  <td>{{$value->name}}</td> 
	   <td class="center"> <a href="{{route('admin.basic.rate-type.edit',$value->uuid)}}" target="_blank" class="btn btn-default btn-sm btn-icon icon-left"> <i class="entypo-pencil"></i>
Edit
</a> <a href="#" class="btn btn-danger btn-sm btn-icon icon-left"> <i class="entypo-cancel"></i>
Delete
</a> <a href="#" class="btn btn-info btn-sm btn-icon icon-left"> <i class="entypo-info"></i>
Profile
</a></td>
	   </tr> 

	 	@endforeach

	   </tbody> 
	   <tfoot> 
	   	<tr>
	   	 <th>SNo</th> 
	   	 <th>Category Name</th>  
	   	 <th>Status</th>
	   	 
	   	</tr> 
	   </tfoot> 
	</table> <br />
 
 <script type="text/javascript">
	jQuery( document ).ready( function( $ ) {
var $table4 = jQuery( "#table-4" );
$table4.DataTable( {
dom: 'Bfrtip',
buttons: [
'copyHtml5',
'excelHtml5',
'csvHtml5',
'pdfHtml5'
]
} );
} );
</script> <br />
@endsection 