routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

	Route::get('/', function () {
    return view('auth.login');
  });
	Auth::routes();



/**
 * Admin Panel
 */
	Route::group(['prefix' => 'admin','middleware' => 'auth'], function () {

  
		Route::get('/dashboard','Admin\DashboardController@index')->name('admin.dashboard.index');
		Route::group(['prefix'=>'bill'],function()
		{
		Route::resource('invoice','Admin\InvoiceController',['as'=>'admin.bill']);
		});
		Route::group(['prefix'=>'basic'],function()
		{
		Route::resource('category','Admin\CategoryController',['as'=>'admin.basic']);
		Route::resource('categorywise-rate','Admin\CategorywiseRateController',['as'=>'admin.basic'],['only'=>'index','create','store']);
		Route::resource('rate-type','Admin\RateTypeController',['as'=>'admin.basic']);
		});
	
	
		});
	

resources/views/layouts/admin/footer.blade.php
 <footer class="main"> <div class="pull-right"> <a href="https://themeforest.net/item/neon-bootstrap-admin-theme/6434477?ref=Laborator" target="_blank"><strong>Purchase this theme for $25</strong></a> </div>
		&copy; 2020 <strong>Neon</strong> Admin Theme by <a href="https://laborator.co/" target="_blank">Laborator</a>
		 </footer>
     <link rel="stylesheet" href=" {{ asset('assets/js/datatables/datatables.css') }}" id="style-resource-1">
      
		 <link rel="stylesheet" href="{{ asset('assets/js/select2/select2-bootstrap.css') }}" id="style-resource-1"> <link rel="stylesheet" href=" {{ asset('assets/js/select2/select2.css') }}" id="style-resource-2"> <link rel="stylesheet" href=" {{ asset('assets/js/selectboxit/jquery.selectBoxIt.css') }}" id="style-resource-3"> <link rel="stylesheet" href="{{ asset('assets/js/daterangepicker/daterangepicker-bs3.css') }}" id="style-resource-4"> <link rel="stylesheet" href=" {{ asset('assets/js/icheck/skins/minimal/_all.css') }}" id="style-resource-5"> <link rel="stylesheet" href="{{ asset('assets/js/icheck/skins/square/_all.css') }}" id="style-resource-6"> <link rel="stylesheet" href="{{ asset('assets/js/icheck/skins/flat/_all.css') }}" id="style-resource-7"> <link rel="stylesheet" href="{{ asset('assets/js/icheck/skins/futurico/futurico.css') }}" id="style-resource-8"> <link rel="stylesheet" href="{{ asset('assets/js/icheck/skins/polaris/polaris.css') }}" id="style-resource-9">
     




<script src="{{ asset('assets/js/gsap/TweenMax.min.js') }}" id="script-resource-1"></script> 
<script src="{{ asset('assets/js/jquery-ui/js/jquery-ui-1.10.3.minimal.min.js') }}" id="script-resource-2"></script> <script src="{{ asset('assets/js/bootstrap.js') }}" id="script-resource-3"></script>
<script src="{{ asset('assets/js/joinable.js') }}" id="script-resource-4"></script>
 <script src=" {{ asset('assets/js/resizeable.js') }}" id="script-resource-5"></script> 
 <script src=" {{ asset('assets/js/neon-api.js') }}" id="script-resource-6"></script> 
 <script src=" {{ asset('assets/js/cookies.min.js') }}" id="script-resource-7"></script>
  <script src=" {{ asset('assets/js/datatables/datatables.js') }}" id="script-resource-8"></script>
  <script src="{{ asset('assets/js/select2/select2.min.js') }}" id="script-resource-8"></script> 
     <script src="{{ asset('assets/js/bootstrap-tagsinput.min.js') }}" id="script-resource-9"></script> 
     <script src="{{ asset('assets/js/typeahead.min.js') }}" id="script-resource-10"></script> 

     <script src="{{ asset('assets/js/selectboxit/jquery.selectBoxIt.min.js') }}" id="script-resource-11"></script>

 <script src="{{ asset('assets/js/jquery.validate.min.js') }}" id="script-resource-8"></script>
  <script src="{{ asset('assets/js/bootstrap-switch.min.js') }}" id="script-resource-8"></script> 
  <script src=" {{ asset('assets/js/neon-chat.js') }}" id="script-resource-9"></script> <!-- JavaScripts initializations and stuff -->
   <script src="{{ asset('assets/js/neon-custom.js') }}" id="script-resource-10"></script> <!-- Demo Settings --> 
   <script src="{{ asset('assets/js/neon-demo.js') }}" id="script-resource-11"></script> 
   <script src="{{ asset('assets/js/neon-skins.js') }}" id="script-resource-12"></script> 
    <script src="{{ asset('assets/js/bootstrap-datepicker.js') }}" id="script-resource-12"></script>
       <script src="{{ asset('assets/js/bootstrap-timepicker.min.js') }}" id="script-resource-13"></script> 
     <script src="{{ asset('assets/js/bootstrap-colorpicker.min.js') }}" id="script-resource-14"></script> 
     <script src="{{ asset('assets/js/moment.min.js') }}" id="script-resource-15"></script> 
     <script src="{{ asset('assets/js/daterangepicker/daterangepicker.js') }}" id="script-resource-16"></script>
    <script src="{{ asset('assets/js/jquery.multi-select.js') }}" id="script-resource-17"></script> 
   <script type="text/javascript">
 var _gaq = _gaq || [];
 _gaq.push(['_setAccount', 'UA-28991003-7']);
 _gaq.push(['_setDomainName', 'demo.neontheme.com']);
 _gaq.push(['_trackPageview']);
 (function() {
  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
 })();
</script> </body> 
<!-- Mirrored from demo.neontheme.com/forms/main/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Dec 2020 06:02:08 GMT -->
</html>

resources/views/layouts/admin/header.blade.php
<!DOCTYPE html> <html lang="en"> 
<!-- Mirrored from demo.neontheme.com/forms/main/ by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 23 Dec 2020 06:02:07 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1" /> <meta name="description" content="Neon Admin Panel" /> <meta name="author" content="Laborator.co" /> <link rel="icon" href="/assets/images/favicon.ico"> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-141030632-1"></script> <script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-141030632-1', {"groups":"laborator_analytics","link_attribution":true,"linker":{"accept_incoming":true,"domains":["laborator.co","kaliumtheme.com","oxygentheme.com","neontheme.com","themeforest.net","laborator.ticksy.com"]}});</script>
 <title>@yield('title')</title>

  <link rel="stylesheet" href="{{ asset('assets/js/jquery-ui/css/no-theme/jquery-ui-1.10.3.custom.min.css') }}
" id="style-resource-1"> <link rel="stylesheet" href="{{ asset('assets/css/font-icons/entypo/css/entypo.css') }}" id="style-resource-2"> <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic" id="style-resource-3"> <link rel="stylesheet" href="{{ asset('assets/css/bootstrap.css') }}" id="style-resource-4"> <link rel="stylesheet" href="{{ asset('assets/css/neon-core.css') }}
" id="style-resource-5"> <link rel="stylesheet" href="{{ asset('assets/css/neon-theme.css') }}
" id="style-resource-6"> <link rel="stylesheet" href="{{ asset('assets/css/neon-forms.css') }}" id="style-resource-7"> <link rel="stylesheet" href="{{ asset('assets/css/custom.css') }}" id="style-resource-8"> <script src="{{ asset('assets/js/jquery-1.11.3.min.js') }}
"></script>
  @yield('header-style')
</head>

 <body class="page-body" data-url="https://demo.neontheme.com"> <!-- TS160870329417455: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates -->
  <div class="page-container"> <!-- TS1608703294702: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates --> 
  	<div class="sidebar-menu"> 
  		<div class="sidebar-menu-inner">
  		 <header class="logo-env"> <!-- logo --> 
  		 	<div class="logo"> <a href="/dashboard/main/index.html"> <img src="/assets/images/logo%402x.png" width="120" alt="" /> </a> </div> <!-- logo collapse icon --> 
  		 	<div class="sidebar-collapse"> <a href="#" class="sidebar-collapse-icon"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition --> <i class="entypo-menu"></i> </a> 
  		 	</div> <!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) --> <div class="sidebar-mobile-menu visible-xs"> <a href="#" class="with-animation"><!-- add class "with-animation" to support animation --> <i class="entypo-menu"></i> </a> </div> </header>
 @include('layouts.admin.sidemenu')
</div> </div>
 <div class="main-content">


 <!-- TS16087032946490: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates --> 
@include('layouts.admin.top-header')
 @yield('content-header')
 @yield('content-body')


 @include('layouts.admin.footer') 

@yield('footer-includes')
@yield('footer-script')

resources/views/layouts/admin/sidemenu.blade.php
<div class="sidebar-menu"> <div class="sidebar-menu-inner"> 
	 <ul id="main-menu" class="main-menu" > 
	 	<li> 
	 		<a href="{{route('admin.dashboard.index')}}"><i class="entypo-gauge"></i><span class="title">Dashboard</span></a> 
 	    </li>

 	   <li> <a href="frontend/main/index.html" target="_blank"><i class="entypo-newspaper"></i><span class="title">Category Rate</span></a> </li>
     <li class="has-sub"> <a href="ui/panels/index.html"><i class="entypo-monitor"></i><span class="title">Billing</span></a>
     <ul> 
     	<li> <a href="{{route('admin.bill.invoice.index')}}"><span class="title">Invoice</a> </li>
        <li> <a href="ui/tiles/index.html"><span class="title">Tiles</span></a> </li> 
     </ul>
     </li>
	 <li class="has-sub"> <a href="extra/icons/index.html"><i class="entypo-bag"></i><span class="title">Extra</span><span class="badge badge-info badge-roundless">New Items</span></a> 
      	<ul>
         <li class="has-sub"> <a href="extra/icons/index.html"><span class="title">Icons</span><span class="badge badge-success">3</span></a> 
             <ul> 
             	 <li> <a href="extra/icons-fontawesome/index.html"><span class="title">Font Awesome</span></a> </li> 
             	 <li> <a href="extra/icons-entypo/index.html"><span class="title">Entypo</span></a> </li>
                 <li> <a href="extra/icons-glyphicons/index.html"><span class="title">Glyph Icons</span></a> </li>
              </ul>
          </li> 
         <li> <a href="extra/charts/index.html"><i class="entypo-chart-bar"></i><span class="title">Charts</span></a> </li>
         <li class="has-sub"> <a href="index.html#"><i class="entypo-flow-tree"></i><span class="title">Menu Levels</span></a>
         </li> 
        </ul> 
        <li class="has-sub"> 
 		 <a href="#"><span class="title"> <i class="entypo-layout"></i>Basic</span></a>
	 		<ul class="visible"> 
		 		<li> <a href="{{route('admin.basic.category.index')}}"><span class="title">Category List</span></a> </li> 
				 <li class=" active ">  <a href="{{route('admin.basic.rate-type.index')}}"><span class="title">Rate Type List</span></a> </li>
		 	    <li> <a href="{{route('admin.basic.categorywise-rate.index')}}"><span class="title">Categorywise Rate</span></a> </li>    	
	        </ul>
 		</li>
 		</div> 
 </div> 

resources/views/layouts/admin/success-error.blade.php
@if(Session::has('flash_message'))
    <div class="tile-body">
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Success!</strong> {{ Session::get('flash_message') }}
        </div>
    </div>
@endif


@if($errors->any())
    <div class="tile-body">
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>Warning!</strong> Mandatory fields / Server Error !!!.
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    </div>
@endif

resources/views/layouts/admin/top-header.blade.php
 <div class="row"> <!-- Profile Info and Notifications --> 

 	<div class="col-md-6 col-sm-8 clearfix">
  <ul class="user-info pull-left pull-none-xsm"> <!-- Profile Info -->
		  <li class="profile-info dropdown"><!-- add class "pull-right" if you want to place this from right --> <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <img src="{{ asset('assets/images/thumb-1%402x.png') }}" alt="" class="img-circle" width="44" />
			John Henderson
				</a>
				 <ul class="dropdown-menu"> <!-- Reverse Caret --> 
						 	<li class="caret"></li> <!-- Profile sub-links --> 
						 	<li> 
						 		<a href="extra/timeline/index.html"> <i class="entypo-user"></i>
							Edit Profile
						</a> </li>
						 <li> <a href="mailbox/main/index.html"> <i class="entypo-mail"></i>
							Inbox
						</a> </li>
						 <li> <a href="extra/calendar/index.html"> <i class="entypo-calendar"></i>
							Calendar
						</a> </li>
						 <li> <a href="#"> <i class="entypo-clipboard"></i>
							Tasks
						</a> </li>
				 </ul>
		  </li>
 </ul> 

<ul class="user-info pull-left pull-right-xs pull-none-xsm"> <!-- Raw Notifications --> 
	<li class="notifications dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> <i class="entypo-attention"></i> <span class="badge badge-info">6</span> </a> <ul class="dropdown-menu"> <!-- TS16087032713165: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates --> 
		<li class="top"> <p class="small"> <a href="#" class="pull-right">Mark all Read</a>
	You have <strong>3</strong> new notifications.
			</p> </li>
 <li> 
		 	<ul class="dropdown-menu-list scroller">
		 	 <li class="unread notification-success"> <a href="#"> <i class="entypo-user-add pull-right"></i> <span class="line"> <strong>New user registered</strong> </span> <span class="line small">
			  30 seconds ago
				</span> </a> 
			</li> 
			<li class="unread notification-secondary"> <a href="#"> <i class="entypo-heart pull-right"></i> <span class="line"> <strong>Someone special liked this</strong> </span> <span class="line small">
			2 minutes ago
			</span> </a> 
			</li>
			 <li class="notification-primary"> <a href="#"> <i class="entypo-user pull-right"></i> <span class="line"> <strong>Privacy settings have been changed</strong> </span>
			  <span class="line small">
			3 hours ago
				</span> </a>
			 </li> 
			<li class="notification-danger"> <a href="#"> <i class="entypo-cancel-circled pull-right"></i> <span class="line">
				John cancelled the event
			</span> <span class="line small">
				9 hours ago
			</span> </a>
			 </li>
			  <li class="notification-info"> <a href="#"> <i class="entypo-info pull-right"></i> <span class="line">
			The server is status is stable
		</span> <span class="line small">
			yesterday at 10:30am
		</span> </a> </li> 
		<li class="notification-warning"> <a href="#"> <i class="entypo-rss pull-right"></i> <span class="line">
			New comments waiting approval
		</span> <span class="line small">
			last week
		</span> </a> 
		</li>
		 </ul> 

</li> 

<li class="external">
 <a href="#">View all notifications</a>
  </li>
</ul>
 </li> 

 <!-- Message Notifications --> 
 <li class="notifications dropdown"> 
 	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> <i class="entypo-mail"></i> <span class="badge badge-secondary">10</span> </a> 
 	<ul class="dropdown-menu"> <!-- TS160870327110664: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates -->
 	 <li> 
 	 	<form class="top-dropdown-search"> <div class="form-group"> <input type="text" class="form-control" placeholder="Search anything..." name="s" /> </div> </form> 

 	 	<ul class="dropdown-menu-list scroller">
 	 	 <li class="active"> <a href="#"> <span class="image pull-right"> <img src="{{ asset('assets/images/thumb-1%402x.png') }}" width="44" alt="" class="img-circle" /> </span> <span class="line"> <strong>Luc Chartier</strong>
	- yesterday
		</span> <span class="line desc small">
			This ain’t our first item, it is the best of the rest.
		</span> </a> 
	
	</li> 
	<li class="active"> <a href="#"> <span class="image pull-right"> <img src="{{ asset('assets/images/thumb-2%402x.png') }}" width="44" alt="" class="img-circle" /> </span> <span class="line"> <strong>Salma Nyberg</strong>
	- 2 days ago
</span> <span class="line desc small">
	Oh he decisively impression attachment friendship so if everything. 
</span> </a> </li>

 <li> <a href="#"> <span class="image pull-right"> <img src="{{ asset('assets/images/thumb-3%402x.png') }}
" width="44" alt="" class="img-circle" /> </span> <span class="line">
	Hayden Cartwright
	- a week ago
</span> <span class="line desc small">
	Whose her enjoy chief new young. Felicity if ye required likewise so doubtful.
</span> </a> 
</li>

 <li> <a href="#"> <span class="image pull-right"> <img src="{{ asset('assets/images/thumb-4%402x.png') }}" width="44" alt="" class="img-circle" /> </span> <span class="line">
	Sandra Eberhardt
	- 16 days ago
</span> <span class="line desc small">
	On so attention necessary at by provision otherwise existence direction.
</span> </a>
 </li>

  </ul> 
</li>
 <li class="external"> <a href="mailbox/main/index.html">All Messages</a> </li>
</ul> 
</li>


 <!-- Task Notifications -->
  <li class="notifications dropdown">
   <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> <i class="entypo-list"></i>
    <span class="badge badge-warning">1</span> 
   </a>

    <ul class="dropdown-menu"> 
     	<!-- TS160870327113499: Xenon - Boostrap Admin Template created by Laborator / Please buy this theme and support the updates --> 
     	<li class="top"> <p>You have 6 pending tasks</p> </li> 
     	<li>
     	<ul class="dropdown-menu-list scroller">
     	  <li> <a href="#"> <span class="task"> <span class="desc">Procurement</span> <span class="percent">27%</span> </span> <span class="progress"> <span style="width: 27%;" class="progress-bar progress-bar-success"> <span class="sr-only">27% Complete</span> </span> </span> </a>
     	  </li>
     	   <li> <a href="#"> <span class="task"> <span class="desc">App Development</span> <span class="percent">83%</span> </span> <span class="progress progress-striped"> <span style="width: 83%;" class="progress-bar progress-bar-danger"> <span class="sr-only">83% Complete</span> </span> </span> </a> 
     	   </li> 
     	   <li> <a href="#"> <span class="task"> <span class="desc">HTML Slicing</span> <span class="percent">91%</span> </span> <span class="progress"> <span style="width: 91%;" class="progress-bar progress-bar-success"> <span class="sr-only">91% Complete</span> </span> </span> </a> 
     	   </li> 
     	   <li> <a href="#"> <span class="task"> <span class="desc">Database Repair</span> <span class="percent">12%</span> </span> <span class="progress progress-striped"> <span style="width: 12%;" class="progress-bar progress-bar-warning"> <span class="sr-only">12% Complete</span> </span> </span> </a> 
     	   </li>
     	   <li> <a href="#"> <span class="task"> <span class="desc">Backup Create Progress</span> <span class="percent">54%</span> </span> <span class="progress progress-striped"> <span style="width: 54%;" class="progress-bar progress-bar-info"> <span class="sr-only">54% Complete</span> </span> </span> </a> 
     	   </li> 
     	   <li> <a href="#"> <span class="task"> <span class="desc">Upgrade Progress</span> <span class="percent">17%</span> </span> <span class="progress progress-striped"> <span style="width: 17%;" class="progress-bar progress-bar-important"> <span class="sr-only">17% Complete</span> </span> </span> </a>
     	    </li> 
     	</ul> 
        </li> 
        <li class="external"> <a href="#">See all tasks</a> </li>
    </ul>
  </li>
 </ul>

  </div>
   <!-- Raw Links -->
    <div class="col-md-6 col-sm-4 clearfix hidden-xs"> <ul class="list-inline links-list pull-right"> <li class="dropdown language-selector">
	Language: &nbsp;


	<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-close-others="true"> <img src="{{ asset('assets/images/flags/flag-uk.png') }}" width="16" height="16" /> </a> <ul class="dropdown-menu pull-right"> <li> <a href="#"> <img src="{{ asset('assets/images/flags/flag-de.png') }}" width="16" height="16" /> <span>Deutsch</span> </a> </li> <li class="active"> <a href="#"> <img src="{{ asset('assets/images/flags/flag-uk.png') }}" width="16" height="16" /> <span>English</span> </a> </li> <li> <a href="#"> <img src="{{ asset('assets/images/flags/flag-fr.png') }}" width="16" height="16" /> <span>François</span> </a> </li> <li> <a href="#"> <img src="{{ asset('assets/images/flags/flag-al.png') }}
" width="16" height="16" /> <span>Shqip</span> </a> </li> <li> <a href="#"> <img src="{{ asset('assets/images/flags/flag-es.png') }}
" width="16" height="16" /> <span>Español</span> </a> </li> </ul> </li> <li class="sep"></li> <li> <a href="#" data-toggle="chat" data-collapse-sidebar="1"> <i class="entypo-chat"></i>
		Chat
		<span class="badge badge-success chat-notifications-badge is-hidden">0</span> </a> </li> <li class="sep"></li> <li> 
  <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><span class="font-icon glyphicon glyphicon-log-out"></span>Logout <i class="entypo-logout right"></i> </a>
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">{{ csrf_field() }}</form> </li> </ul>

			 </div>

			  </div> <hr />